name: Build and Publish Natives to Github Packages
permissions:
  packages: write
on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  build-linux-windows:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_REPOSITORY: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Install cross-compilation toolchains
        run: |
          sudo apt update
          sudo apt install -y --force-yes gcc g++ mingw-w64
          sudo apt install -y --force-yes gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build natives for Linux/Windows
        run: |
          ./gradlew :luajit:jnigen :luajit:jnigenBuildLinux64 :luajit:jnigenBuildWindows64
          ./gradlew :lua54:jnigen :lua54:jnigenBuildLinux64 :lua54:jnigenBuildWindows64
      - name: Publish to GitHub Packages (GHCR)
        run: |
          ./gradlew :luajit:publish :lua54:publish --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}